export { default as PageTitle } from './PageTitle'
export { default as DisplayTitle } from './DisplayTitle'
export { default as SectionTitle } from './SectionTitle'
export { default as BodyText } from './BodyText'
export { default as Caption } from './Caption'

export { default as HeroHeadline } from './HeroHeadline'
export { default as EditorialHeading } from './EditorialHeading'
export { default as FloatingMetadata } from './FloatingMetadata'
export { default as GradientTitle } from './GradientTitle'
export { default as KineticCaption } from './KineticCaption'
export { default as CinematicDescription } from './CinematicDescription'
